server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul-filter
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8761/eureka/
    healthcheck:
      enable: true
  instance:
    prefer-ip-address: true # 将自己的IP注册到Eureka Server。若不配置或设置为false，表示注册微服务所在操作系统的hostname到Eureka Server
#Actuator打开默认端点http://localhost:8040/actuator/routes
management:
  endpoints:
    web:
      exposure:
        include: routes
zuul:  routes:    microservice-provider-user: /user/**
    #microservice-hystrix-dashboad: /dashboad/**