spring:
  application:
    name: microservice-descovery-eureka-ha
server:
  port: 8761
eureka:
  server:
    enable-self-preservation:false
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8762/eureka