spring:
  application:
    name: microservice-descovery-eureka-ha
server:
  port: 8762
eureka:
  server:
    enable-self-preservation:false
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka