server:
  port: 8010
  
spring:
  application: #增加注册eureka的服务名称
    name: microservice-consumer-moive
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: admin
    password: admin
    virtualHost: /
    listener:
      direct:
        retry:
          enabled: true
eureka: #增加eureka client的主要配置信息
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true #使用health端点来代替心跳表明服务是否可用,反应到eureka server ui上服务的UP还是DOWN
management:
  endpoint:
      web:
        exposure:
            include: "*"
      health:
        show-details: always