server:
  port: 8010
spring:  application:    name: microservice-consumer-moive
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: admin
    password: admin
    listener:
      type: direct # simple direct
#  zipkin: #链路信息将发送到MQ，zipkin在从MQ采集，故不要直接再将链路信息发送给zipkin
#    base-url: http://192.168.99.100:9411
  sleuth:
    traceId128: true
    sampler:
      probability: 1.0 #采样的比例.默认是0.1即10%,建议在测试时设置为1.0，因为在分布式系统中数据量会非常大,采样非常重要
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG