server:
  port: 8081
logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      #base-path: / #默认是/actuator 前缀，可以在这里修改
      exposure:
        include: "*"
spring:
  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: guest
    password: guest