server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false #设为false，关闭自我保护，从而保证会注销微服务
    eviction-interval-time-in-ms: 10000	 #清理间隔（单位毫秒，默认是60*1000）
  client:
    register-with-eureka: false 	# 是否将自己注册到Eureka Server，默认为true。由于当前应用就是Eureka Server，故而设为false
    fetch-registry: false 					# 表示是否从Eureka Sever获取注册信息，默认为true。因为这个一个单节点的Eureka Server，不需要同步其他的Eureka Server节点的数据，故而设为false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka # 设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。