server:
  port: 8010
  
spring:
  application: #增加注册eureka的服务名称
    name: microservice-consumer-moive
 
eureka: #增加eureka client的主要配置信息
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true #使用health端点来代替心跳表明服务是否可用,反应到eureka server ui上服务的UP还是DOWN
management:
  endpoints:
    web:
      exposure:
        include: "*"
#将Feign接口的日志级别设置成DEBUG,因为Feign的Logger.Level只针对DEBUG做出响应
logging:
  level:
    com.itmuch.cloud.microserviceconsumermovie.feign.UserFeignClient: DEBUG